# Generated by Django 3.1.14 on 2021-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
