# Generated by Django 3.1.14 on 2021-12-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211227_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_charge',
            field=models.IntegerField(default=100),
        ),
    ]
